markdown: redcarpet
paginate: 4
permalink: none

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      categories: ['article','training']

page_gen:
  - data: 'texas'
    template: 'ticket'
    name: 'name'
    drname: 'dname'
gems:
 - jekyll-sitemap
